name: Dispatcher
on:
  repository_dispatch:
jobs:
  dispatch:
    runs-on: [ubuntu-latest]
    steps:
      #- uses: actions/checkout@v2
      #  with:
      #      ref: ${{github.head_ref}}
      - name: set secret
        run: |
          echo "reveived hook"
          suffix="${{github.event.client_payload.repo}}"
          echo "$suffix"|cut -d '/' -f 2|grep 'homework'
          if [ $? -eq 0 ]
          then
            echo "homework"
          fi
          echo "$suffix"

      #- name: PrintEnv
      #  env:
      #    GITHUB_CONTEXT: ${{ toJSON(github) }}
      #  run: |
      #    echo event triggered.
      #    echo "$GITHUB_CONTEXT"
