name: Dispatcher
on:
  repository_dispatch:
jobs:
  dispatch:
    runs-on: [ubuntu-latest]
    if: ${{github.event.client_payload.action == 'created'}}
    steps:
      - uses: actions/checkout@v2
      - name: set secret
        env:
          token: ${{secrets.workflow_token}}
        #working-directory: ${{github.workspace}}
        run: |
          echo "reveived hook"
          bash setup.sh "${{github.event.client_payload.repo}}"
  #log:
  #  runs-on: [ubuntu-latest] 
  #  steps:
  #    - name: log
  #      run: |
          echo "${{github.event.client_payload.action}}"
    

      #- name: PrintEnv
      #  env:
      #    GITHUB_CONTEXT: ${{ toJSON(github) }}
      #  run: |
      #    echo event triggered.
      #    echo "$GITHUB_CONTEXT"
