name: Dispatcher
on:
  repository_dispatch:
jobs:
  dispatch:
    runs-on: [ubuntu-latest]
    steps:
      #- uses: actions/checkout@v2
      #  with:
      #      ref: ${{github.head_ref}}
      - name: set secret
        run: |
          echo "reveived hook"
          bash setup.sh "${{github.event.client_payload.repo}}"

      #- name: PrintEnv
      #  env:
      #    GITHUB_CONTEXT: ${{ toJSON(github) }}
      #  run: |
      #    echo event triggered.
      #    echo "$GITHUB_CONTEXT"
